// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0bgl-W2W9mzCLGUHxZxU4WMUdwqwnqg',
    appId: '1:531308153598:web:61c13d9603fe03e6cd33af',
    messagingSenderId: '531308153598',
    projectId: 'my-first-project-48de0',
    authDomain: 'my-first-project-48de0.firebaseapp.com',
    storageBucket: 'my-first-project-48de0.appspot.com',
    measurementId: 'G-CWZ5QS2X17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiA-NIzKyud79zsRxo8V9DQVK23oZY9aI',
    appId: '1:531308153598:android:fb6f8dab7fce9295cd33af',
    messagingSenderId: '531308153598',
    projectId: 'my-first-project-48de0',
    storageBucket: 'my-first-project-48de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkZEqTiRVWU3SCgyHfZ0bQOykp6gG7Eo',
    appId: '1:531308153598:ios:f16529d607b803c8cd33af',
    messagingSenderId: '531308153598',
    projectId: 'my-first-project-48de0',
    storageBucket: 'my-first-project-48de0.appspot.com',
    iosBundleId: 'com.example.practiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkZEqTiRVWU3SCgyHfZ0bQOykp6gG7Eo',
    appId: '1:531308153598:ios:93cb48905e79d365cd33af',
    messagingSenderId: '531308153598',
    projectId: 'my-first-project-48de0',
    storageBucket: 'my-first-project-48de0.appspot.com',
    iosBundleId: 'com.example.practiesApp.RunnerTests',
  );
}
